[server]

# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 50

[theme]

base="dark"

[browser]
gatherUsageStats = false